import { NextRequest, NextResponse } from "next/server";
import fs from "fs";
import path from "path";
import { client } from "@/lib/client";

const ERC20_BALANCE_ABI = [
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

// Read an ERC20 balance on-chain (X Layer testnet) via the viem public client.
// Returns "0" if the contract doesn't exist or the call reverts.
async function getBalance(token: string, owner: string): Promise<string> {
  try {
    const bal = (await client.readContract({
      address: token as `0x${string}`,
      abi: ERC20_BALANCE_ABI,
      functionName: "balanceOf",
      args: [owner as `0x${string}`],
    })) as bigint;
    return bal.toString();
  } catch {
    return "0";
  }
}

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const address = searchParams.get("address");
    const team = searchParams.get("team");
    const position = searchParams.get("position");
    const search = searchParams.get("search");
    const showAll = searchParams.get("showAll") === "true";

    if (!address) {
      return NextResponse.json(
        { error: "Missing address parameter" },
        { status: 400 }
      );
    }

    // Read the player registry file to get valid contract addresses.
    // Generated by `npm run deploy-all` (World Cup league 1, season 2022,
    // Argentina). Re-run deploy-all to refresh.
    const registryPath = path.join(
      process.cwd(),
      "..",
      "contracts",
      "enhanced-player-data-1-2022.json"
    );
    const registryData = JSON.parse(fs.readFileSync(registryPath, "utf8"));

    // Create a map of contract addresses to player data for quick lookup
    const playerRegistry = new Map();
    registryData.players.forEach((player: any) => {
      playerRegistry.set(player.tokenAddress.toLowerCase(), {
        playerId: player.playerId,
        playerName: player.playerName,
        teamName: player.teamName,
        position: player.position,
        teamCode: player.teamCode,
        teamLogo: player.teamLogoUrl,
        teamVenue: player.teamVenue,
        teamContractAddress: player.teamContractAddress,
        teamId: player.teamId,
        image: player.photoUrl,
        tokenName: player.tokenName,
        tokenSymbol: player.tokenSymbol,
        deployedAt: player.deploymentTime,
      });
    });

    // Fetch on-chain balances for every registry token in parallel.
    const entries = Array.from(playerRegistry.entries());
    const balances = await Promise.all(
      entries.map(([contractAddress]) =>
        getBalance(contractAddress as string, address)
      )
    );

    let filteredTokens = entries
      .map(([contractAddress, playerData], i) => {
        const balance = balances[i];
        const isOwned = BigInt(balance) > BigInt(0);
        return {
          contractAddress: contractAddress as string,
          tokenName: playerData.tokenName,
          tokenSymbol: playerData.tokenSymbol,
          balance,
          isOwned,
          playerData,
        };
      })
      // In owned-only mode, drop tokens the user holds none of.
      .filter((token) => showAll || token.isOwned);

    // Apply additional filters
    if (team) {
      filteredTokens = filteredTokens.filter((token: any) =>
        token.playerData.teamName.toLowerCase().includes(team.toLowerCase())
      );
    }

    if (position) {
      filteredTokens = filteredTokens.filter(
        (token: any) =>
          token.playerData.position.toLowerCase() === position.toLowerCase()
      );
    }

    if (search) {
      filteredTokens = filteredTokens.filter(
        (token: any) =>
          token.playerData.playerName
            .toLowerCase()
            .includes(search.toLowerCase()) ||
          token.playerData.tokenSymbol
            .toLowerCase()
            .includes(search.toLowerCase())
      );
    }

    return NextResponse.json({
      success: true,
      data: filteredTokens,
      total: filteredTokens.length,
      address: address,
      leagueId: registryData.leagueId,
      season: registryData.season,
      lastUpdated: registryData.fetchTime,
      filters: {
        team: team || null,
        position: position || null,
        search: search || null,
        showAll: showAll,
      },
    });
  } catch (error) {
    console.error("Error fetching token holdings:", error);
    return NextResponse.json(
      {
        error: "Failed to fetch token holdings",
        details: error instanceof Error ? error.message : String(error),
      },
      { status: 500 }
    );
  }
}
